name: intl_script_recognizer
description: Handle the Locale which offer script language only to corresponded region code in intl package
version: 1.0.0
repository: https://github.com/rk0cc/intl_script_recognizer
funding: https://github.com/sponsors/rk0cc
environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.12"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  quiver: ">=3.2.1 <3.3.0"
  country_code: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

