name: intl_script_recognizer
description: Handle the Locale which offer script language only to corresponded region code in intl package
version: 2.2.0
repository: https://github.com/rk0cc/intl_script_recognizer
topics:
  - intl
  - locale
  - l10n
  - localization
funding:
  - https://github.com/sponsors/rk0cc
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

