name: Unit test 
on:
  push:
    branches:
      - main
    paths:
      - lib/**.dart
      - test/**.dart
      - pubspec.yaml
      - .github/workflows/flutter_test.yml
  pull_request:
    branches:
     - main
jobs:
  testing:
    name: Flutter test
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initalize Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Perform test
        run: flutter test